site/code/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :activities
  get '', to: 'home#index'
  get 'dashboard', to: 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

site/code/app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
end

site/code/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

site/code/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :activities
end

site/code/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user_id = current_user.id

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activities_url, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activities_url, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :category, :tags, :status, :story_points, :hours)
    end
end

site/code/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

site/code/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  # GET /dashboard
  def index
    @graph_story_hours = get_graph_story_hours
  end

  def get_graph_story_hours
    map = {}
    [1, 2, 3, 5, 8, 13].each do |number|
      map["SP-#{number}"] = Activity.where(story_points: number).average(:hours)
    end
    map
  end
end

site/code/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
        redirect_to activities_url
    else
        redirect_to new_user_session_url
    end
  end
end

site/code/app/helpers/activities_helper.rb
module ActivitiesHelper
end

site/code/app/helpers/application_helper.rb
module ApplicationHelper
end

site/code/app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :category %>
    <%= form.text_field :category, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tags %>
    <%= form.text_field :tags, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= form.label :status %>
      <%= form.select :status, ['Concluded', 'Doing'], {}, class: 'form-control' %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :story_points %>
      <%= form.select :story_points, [1, 3, 5, 8, 13, 21, 34, 55, 89, 144], {}, class: 'form-control' %>
    </div>

    <div class="form-group col-md-4">
      <%= form.label :hours %>
      <%= form.number_field :hours, class: 'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

site/code/app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

site/code/app/views/activities/index.html.erb
<h1>Activities</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Tags</th>
      <th>Status</th>
      <th>Story points</th>
      <th>Hours</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.category %></td>
        <td><%= activity.tags %></td>
        <td><%= activity.status %></td>
        <td><%= activity.story_points %></td>
        <td><%= activity.hours %></td>
        <td>
          <%= link_to 'Edit', edit_activity_path(activity), class: 'btn btn-sm btn-primary' %>
          <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path, class: 'btn btn-primary' %>

site/code/app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

site/code/app/views/activities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @activity.category %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @activity.tags %>
</p>

<p>
  <strong>Status:</strong>
  <%= @activity.status %>
</p>

<p>
  <strong>Story points:</strong>
  <%= @activity.story_points %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

site/code/app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-6">
    <canvas id="graphPointsHours" width="100%" height="70" />
  </div>
  <div class="col-md-6">
  </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script type="text/javascript">
	var ctx = document.getElementById("graphPointsHours").getContext('2d');
	var myChart = new Chart(ctx, {
			type: 'bar',
			data: {
					labels: <%= raw @graph_story_hours.keys.to_json %>,
					datasets: [{
							label: '# of Votes',
							data: <%= raw @graph_story_hours.values.to_json %>,
							backgroundColor: [
									'rgba(255, 99, 132, 0.2)',
									'rgba(54, 162, 235, 0.2)',
									'rgba(255, 206, 86, 0.2)',
									'rgba(75, 192, 192, 0.2)',
									'rgba(153, 102, 255, 0.2)',
									'rgba(255, 159, 64, 0.2)'
							],
							borderColor: [
									'rgba(255,99,132,1)',
									'rgba(54, 162, 235, 1)',
									'rgba(255, 206, 86, 1)',
									'rgba(75, 192, 192, 1)',
									'rgba(153, 102, 255, 1)',
									'rgba(255, 159, 64, 1)'
							],
							borderWidth: 1
					}]
			},
			options: {
					scales: {
							yAxes: [{
									ticks: {
											beginAtZero:true
									}
							}]
					}
			}
	});
</script>

site/code/app/views/layouts/_left_column.html.erb
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
  <li class="nav-item">
    <a class="nav-link" href="<%= dashboard_url %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= activities_url %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Activities</span>
    </a>
  </li>
</ul>

site/code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EstimationTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body class="<%= user_signed_in? ? '' : 'bg-dark' %>">
   <% if user_signed_in? %>
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
      <a class="navbar-brand mr-1" href="index.html">Estimation Tracker</a>

      <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      </div>

      <!-- Navbar -->
      <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown no-arrow">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user-circle fa-fw"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <!-- <div class="dropdown-divider"></div> -->
            <%= link_to 'Exit', destroy_user_session_url, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </nav>
    <div id="wrapper">
      <%= render partial: 'layouts/left_column' %>
      <div id="content-wrapper">
        <div class="container-fluid">
   <% end %>

    <% if notice %>
    <p class="alert alert-warning"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <% if user_signed_in? %>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>